class pg:
    singlesharing = "/customers_signup0"
    delete = "/customers_delete"
    triplesharing = "/triplesharing"
    doublesharing = "/doublesharing"
    singlesharingwelocome = "/singlesharing"
    welcome = "/booking"
    customerdetails = "/customers_details"
    customersignup = "/customers_signup0"
    triplesharingbooking = "/triplesharing"
    doublesharingbooking = "/doublesharing"
    singlesharingbooking = "/singlesharing"
    userlogin = "/login_user"
    roomupdate = "/roomupdate"
